import express from "express";

const app: express.Express = express();
const port = process.env.PORT || 8080;

app.get("/", (req: express.Request, res: express.Response) => {
  res.send("Hello, world!");
});

app.get("/wakuwaku", (req: express.Request, res: express.Response) => {
  res.send("wakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwakuwaku");
});

app.listen(port, () => {
  console.log(`port ${port} でサーバー起動中`);
});